[tox]
skipsdist=True
skip_missing_interpreters =
    True
envlist =
    py36
    py35

[coverage:run]
branch = True

[coverage:report]
show_missing = True
exclude_lines =
    pragma: no cover
    def __repr__
    def __hash__
    if .debug:
    raise NotImplementedError
    if __name__ == .__main__.:
omit =
    .git/*
    .tox/*
    .env/*
    venv/*
    dist/*
    build/*
    tests/*

[testenv]
deps =
    doc8
    pytest
    pytest-cov
    pytest-flake8
    -rrequirements.txt
commands =
    pytest --basetemp={envtmpdir} --cache-clear -sv --flake8 --cov
    doc8 README.rst
